=== parcel-bundler/parcel/packages/utils/parcelforvscode/schemas/parcelrc.schema.json
{
  "title": "JSON schema for .parcelrc files",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "allowTrailingCommas": true,
  "$defs": {
    "plugin": {
      "type": "string"
    },
    "plugins": {
      "defaultSnippets": [
        {
          "body": ["$1", "..."]
        }
      ],
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "#/$defs/plugin"
      }
    },
    "pluginGlobMap": {
      "type": "object",
      "properties": {},
      "additionalProperties": {
        "$ref": "#/$defs/plugin"
      }
    },
    "pluginsGlobMap": {
      "type": "object",
      "properties": {},
      "additionalProperties": {
        "$ref": "#/$defs/plugins"
      }
    }
  },
  "properties": {
    "extends": {
      "oneOf": [
        {
          "$ref": "#/$defs/plugin"
        },
        {
          "$ref": "#/$defs/plugins"
        }
      ],
      "default": "@parcel/extends-default"
    },
    "bundler": {
      "description": "Transform the entire asset graph by grouping the assets into the output bundles.",
      "$ref": "#/$defs/plugin"
    },
    "resolvers": {
      "description": "Resolve a dependency to a file path or virtual module.",
      "$ref": "#/$defs/plugins"
    },
    "transformers": {
      "description": "Compile individual source files and extract dependencies.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "validators": {
      "description": "Validates individual assets and can throw errors or log warnings with diagnostics to validate the input.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "namers": {
      "description": "Determine the name of an output bundle.",
      "$ref": "#/$defs/plugins"
    },
    "packagers": {
      "description": "Combine multiple assets together into a single output bundle.",
      "$ref": "#/$defs/pluginGlobMap"
    },
    "optimizers": {
      "description": "Minify, optimize, and transform output bundles.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "compressors": {
      "description": "Compress and encode output bundles in multiple formats.",
      "$ref": "#/$defs/pluginsGlobMap"
    },
    "reporters": {
      "description": "Receive events on build progress and completion.",
      "$ref": "#/$defs/plugins"
    },
    "runtimes": {
      "description": "Return additional assets to be inserted into a bundle.",
      "$ref": "#/$defs/plugins"
    }
  },
  "additionalProperties": false,
  "default": {
    "extends": "@parcel/config-default"
  }
}

=== parcel-bundler/parcel/packages/configs/atlassian-ssr/index.json
{
  "extends": ["@parcel/config-default"],
  "transformers": {
    "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
    "bundle-text:*": ["@parcel/transformer-inline-string", "..."],
    "data-url:*": ["@parcel/transformer-inline-string", "..."],
    "*.worker.{js,mjs,jsm,jsx,es6,ts,tsx}": [
      "@parcel/transformer-workerize",
      "..."
    ],
    "*.{js,mjs,jsm,jsx,es6,ts,tsx}": [
      "@parcel/transformer-sync-dynamic-import",
      "@parcel/transformer-babel",
      "@parcel/transformer-js"
    ],
    "*.{json,json5}": ["@parcel/transformer-json"],
    "*.toml": ["@parcel/transformer-toml"],
    "*.yaml": ["@parcel/transformer-yaml"],
    "*.{gql,graphql}": ["@parcel/transformer-graphql"],
    "*.{styl,stylus}": ["@parcel/transformer-stylus"],
    "*.{sass,scss}": ["@parcel/transformer-sass"],
    "*.less": ["@parcel/transformer-less"],
    "*.css": ["@parcel/transformer-postcss", "@parcel/transformer-css"],
    "*.sss": ["@parcel/transformer-sugarss"],
    "*.{htm,html}": [
      "@parcel/transformer-posthtml",
      "@parcel/transformer-html"
    ],
    "*.pug": ["@parcel/transformer-pug"],
    "*.coffee": ["@parcel/transformer-coffeescript"],
    "*.mdx": ["@parcel/transformer-mdx"],
    "*.{eot,gif,jpg,jpeg,ico,mp4,png,svg,ttf,woff}": [
      "@parcel/transformer-raw"
    ],
    "url:*": ["@parcel/transformer-raw"],
    "*": ["@parcel/transformer-not-splittable"]
  },
  "reporters": [
    "@atlassian/parcel-reporter-analytics",
    "@parcel/reporter-manifest",
    "@parcel/reporter-dev-server",
    "@parcel/reporter-bundle-analyzer"
  ],
  "resolvers": ["@parcel/resolver-atlassian-ssr"]
}

=== parcel-bundler/parcel/packages/configs/default/index.json
{
  "bundler": "@parcel/bundler-default",
  "transformers": {
    "types:*.{ts,tsx}": ["@parcel/transformer-typescript-types"],
    "bundle-text:*": ["...", "@parcel/transformer-inline-string"],
    "data-url:*": ["...", "@parcel/transformer-inline-string"],
    "worklet:*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
      "@parcel/transformer-worklet",
      "..."
    ],
    "*.{js,mjs,jsm,jsx,es6,cjs,ts,tsx}": [
      "@parcel/transformer-babel",
      "@parcel/transformer-js",
      "@parcel/transformer-react-refresh-wrap"
    ],
    "*.{json,json5}": ["@parcel/transformer-json"],
    "*.jsonld": ["@parcel/transformer-jsonld"],
    "*.toml": ["@parcel/transformer-toml"],
    "*.webmanifest": ["@parcel/transformer-webmanifest"],
    "webmanifest:*.{json,webmanifest}": ["@parcel/transformer-webmanifest"],
    "*.{yaml,yml}": ["@parcel/transformer-yaml"],
    "*.{glsl,vert,frag}": ["@parcel/transformer-glsl"],
    "*.{gql,graphql}": ["@parcel/transformer-graphql"],
    "*.{styl,stylus}": ["@parcel/transformer-stylus"],
    "*.{sass,scss}": ["@parcel/transformer-sass"],
    "*.less": ["@parcel/transformer-less"],
    "*.{css,pcss}": ["@parcel/transformer-postcss", "@parcel/transformer-css"],
    "*.sss": ["@parcel/transformer-sugarss"],
    "*.{htm,html,xhtml}": [
      "@parcel/transformer-posthtml",
      "@parcel/transformer-html"
    ],
    "*.pug": ["@parcel/transformer-pug"],
    "*.coffee": ["@parcel/transformer-coffeescript"],
    "*.elm": ["@parcel/transformer-elm"],
    "*.mdx": ["@parcel/transformer-mdx"],
    "*.vue": ["@parcel/transformer-vue"],
    "template:*.vue": ["@parcel/transformer-vue"],
    "script:*.vue": ["@parcel/transformer-vue"],
    "style:*.vue": ["@parcel/transformer-vue"],
    "custom:*.vue": ["@parcel/transformer-vue"],
    "*.{png,jpg,jpeg,webp,gif,tiff,avif,heic,heif}": [
      "@parcel/transformer-image"
    ],
    "*.svg": ["@parcel/transformer-svg"],
    "*.txt": ["@parcel/transformer-raw"],
    "*.{xml,rss,atom}": ["@parcel/transformer-xml"],
    "url:*": ["...", "@parcel/transformer-raw"]
  },
  "namers": ["@parcel/namer-default"],
  "runtimes": [
    "@parcel/runtime-js",
    "@parcel/runtime-browser-hmr",
    "@parcel/runtime-react-refresh",
    "@parcel/runtime-service-worker"
  ],
  "optimizers": {
    "data-url:*": ["...", "@parcel/optimizer-data-url"],
    "*.css": ["@parcel/optimizer-css"],
    "*.{html,xhtml}": ["@parcel/optimizer-htmlnano"],
    "*.{js,mjs,cjs}": ["@parcel/optimizer-swc"],
    "*.svg": ["@parcel/optimizer-svgo"],
    "*.{jpg,jpeg,png}": ["@parcel/optimizer-image"]
  },
  "packagers": {
    "*.{html,xhtml}": "@parcel/packager-html",
    "*.css": "@parcel/packager-css",
    "*.{js,mjs,cjs}": "@parcel/packager-js",
    "*.svg": "@parcel/packager-svg",
    "*.{xml,rss,atom}": "@parcel/packager-xml",
    "*.ts": "@parcel/packager-ts",
    "*.wasm": "@parcel/packager-wasm",
    "*.{jsonld,svg,webmanifest}": "@parcel/packager-raw-url",
    "*": "@parcel/packager-raw"
  },
  "compressors": {
    "*": ["@parcel/compressor-raw"]
  },
  "resolvers": ["@parcel/resolver-default"],
  "reporters": ["@parcel/reporter-dev-server"]
}
